version: "3"

services:

  redis:
    container_name: redis
    image: redis:latest
    volumes:
    - "./data/redis:/data"
    ports:
    - "6379:6379"

  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projetonw #sempre alterar para o nome do banco que você vai usar
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
    - "./data/mysql:/var/lib/mysql"
    ports:
    - "3308:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - "PMA_HOSTS=db"
    links:
    - "mysql:db"
    ports:
    - "3380:80"

  php:
    container_name: php
    image: virgilioneto/laravel-ready
    environment:
    - "XDEBUG_CONFIG=remote_host=172.16.43.72"
    volumes:
    - ".:/var/www/html"
    ports:
    - "8000:80"
    - "443:443"